apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsti-devops-project
  labels:
    app: dsti-devops-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dsti-devops-project
  template:
    metadata:
      labels:
        app: dsti-devops-project
    spec:
      containers:
      - name: dsti-devops-project
        image:  bhandari100/dsti-devops-project
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: dsti-devops-project-service
  labels:
    app: dsti-devops-project
spec:
  selector:
    app: dsti-devops-project
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 4000
  type: LoadBalancer
  loadBalancerIP: 10.0.0.100